package searchexercise1;

import java.util.ArrayList;
import java.util.Scanner;
import java.io.File;
import java.io.FileNotFoundException;

/* Jay Ahn
 * Nov 18 2025
 * Program that searches for book
 */
public class SearchExercise1 extends javax.swing.JFrame {

    ArrayList<Book> books = new ArrayList();

    /**
     * Creates new form SearchExercise1
     */
    public SearchExercise1() {
        initComponents();
        try {
            int rNum;
            String title;
            File f = new File("src/searchexercise1/BookList.txt");
            Scanner s = new Scanner(f);
            while (s.hasNextLine()) {
                rNum = Integer.parseInt(s.nextLine());
                title = s.nextLine();
                Book a = new Book(rNum, title);
                books.add(a);
            }
        } catch (FileNotFoundException e) {
            System.out.println("Error: " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblDes = new javax.swing.JLabel();
        lblrNum = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtrNum = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        txtLinS = new javax.swing.JTextField();
        txtBinS = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 0, 51));
        lblTitle.setText("Children's Classics");

        lblDes.setText("This program will find the title of a book based on it's reference number");

        lblrNum.setText("Enter the reference number:");

        jLabel4.setText("Linear Search:");

        jLabel5.setText("Binary Search:");

        btnFind.setText("Find it!");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        txtLinS.setEditable(false);

        txtBinS.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBinS))
                    .addComponent(lblDes)
                    .addComponent(lblTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblrNum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnFind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtrNum)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLinS, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblTitle)
                .addGap(38, 38, 38)
                .addComponent(lblDes)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblrNum)
                    .addComponent(txtrNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnFind)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtLinS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtBinS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        int rNum = Integer.parseInt(txtrNum.getText());
        txtLinS.setText(searchLinear(rNum));
        int index[] = searchBinary(rNum, 0, books.size() - 1, 0);
        String s;
        if (index[0] != -1) {
            s = "Found: " + books.get(index[0]).getTitle() + ". " + index[1] + " books processed";
        } else {
            s = "Book # " + rNum + " is not in the list";
        }
        txtBinS.setText(s);
    }//GEN-LAST:event_btnFindActionPerformed

    private String searchLinear(int rNum) {
        int counter = 1;
        boolean count = true;
        Book a = new Book();
        for (int i = 0; i < books.size(); i++) {
            if (books.get(i).getrNum() == rNum) {
                a = books.get(i);
                count = false;
            }
            if (count) {
                counter++;
            }
        }
        if (a.getTitle().equals("")) {
            return "Book # " + rNum + " is not in the list";
        } else {
            return "Found: " + a.getTitle() + ". " + counter + " books processed";
        }
    }

    private int[] searchBinary(int rNum, int left, int right, int counter) {
        int middle = (left + right) / 2;
        if (left > right) {
            int[] a = {-1, 0};
            return a;
        } else if (books.get(middle).getrNum() == rNum) {
            counter++;
            int[] a = {middle, counter};
            return a;
        } else if (books.get(middle).getrNum() > rNum) {
            counter++;
            return searchBinary(rNum, left, middle - 1, counter);
        } else {
            counter++;
            return searchBinary(rNum, middle + 1, right, counter);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchExercise1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchExercise1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchExercise1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchExercise1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchExercise1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFind;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblDes;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblrNum;
    private javax.swing.JTextField txtBinS;
    private javax.swing.JTextField txtLinS;
    private javax.swing.JTextField txtrNum;
    // End of variables declaration//GEN-END:variables
}
